@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

###

@name = greet

GET http://{{host}}/{{name}}

###

@name = customers

GET http://{{host}}/{{name}}

###

GET http://{{host}}/{{name}}?status=active

###

GET http://{{host}}/{{name}}?status=inactive

###

GET http://{{host}}/{{name}}
content-type: application/xml

###

GET http://{{host}}/{{name}}/2000

###

POST http://{{host}}/{{name}}



